#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 22 11:34:09 2018

@author: Rafiki
"""

import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import mean_squared_error

filt = [0,1,2,3,4,6]
Ir = np.array([0.157, 0.119, 0.096, 0.079, 0.068,	0.052])   

x = np.linspace(0,6,1000)
reg = np.polyfit(filt,Ir,4)
irfit = np.polyval(reg,x)
irmse = np.polyval(reg,filt)


plt.plot(x,irfit,"--",label="Fjerdegrads tilpasning")
plt.plot(filt,Ir,"o", label="Målinger")
plt.xlabel("Ekstra Aluminiumsfilter [mm]",fontsize = 14)
plt.ylabel("Ionerate [nA]",fontsize = 14)
plt.grid(linestyle='-', linewidth=0.5)

plt.title("Ionerate som funksjon ektra aluminiumsfilter", fontsize = 16, fontweight="bold", y=1.08)

hvl = 0
for i in range(len(x)):
    if(abs(irfit[0]/2 - irfit[i]) < 5e-4):
       hvl = i 

hvlmsg = ("HVL = %.3f mm" %(x[hvl]))
plt.plot([x[hvl],x[hvl]],[min(irfit),max(irfit)],"--",color="gray", label=hvlmsg)
#plt.plot([min(x),max(x)],[irfit[hvl],irfit[hvl]],"--",color="gray")
plt.legend()
plt.show()
print(mean_squared_error(Ir,irmse))



ilog = np.log(Ir)
reg = np.polyfit(filt,ilog,1)
irfit = np.polyval(reg,x)
irmse = np.polyval(reg,filt)
plt.plot(x,irfit,"--",label="Førstegrads tilpasning")
plt.plot(filt,ilog,"o", label="Naturlig logaritme av målinger")
plt.xlabel("Ekstra Aluminium [mm]",fontsize = 14)
plt.ylabel("Ionerate [nA]",fontsize = 14)
plt.grid(linestyle='-', linewidth=0.5)
plt.title("Ionerate som funksjon ektra Aluminium", fontsize = 16, fontweight="bold", y=1.08)
plt.legend()
plt.show()

print(reg)
print("HVL = ",np.log(2)/abs(reg[0]))
print(mean_squared_error(Ir,irmse))