#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 23 16:27:21 2018

@author: Rafiki
"""
import matplotlib.pyplot as plt
import numpy as np


V = np.linspace(1e1,2.2e2,22)
murho = [2.141E+2, 3.359E+1, 1.090E+1, 4.854E+0, 2.619E+0, 1.593E+0, 1.063E+0, 7.631E-1, 5.796E-1, 4.604E-1, 3.782E-1, 3.216E-1, 2.789E-1, 2.467E-1, 2.226E-1, 2.032E-1, 1.882E-1, 1.751E-1, 1.653E-1, 1.560E-1, 1.489E-1, 1.424E-1]
hvl = 0.1478 #cm
rho = 8.96 #g/cm^3

mueff = np.log(2)/hvl #1/cm
murhoeff = mueff/rho #cm^2/g

val = 1e10
find = 0
for i in range(len(murho)):
    if(abs(murho[i]-murhoeff) < val):
        val = murho[i]-murhoeff
        find = i
        
fig, ax1 = plt.subplots()


ax1.plot(V,murho,"-",label="Cu attenuasjons koef.")
ax1.plot([min(V),max(V)],[murhoeff,murhoeff],"--",label="HVL attenuasjons koef.")
plt.ylabel("$\mu/\\rho$ [cm$^2$/g]",fontsize = 14)
plt.xlabel("Foton energi [keV]",fontsize = 14)
plt.title('Effektiv energi m/Cu filter ved HVL attenuasjon koef.', fontsize = 16, fontweight="bold", y=1.08)
plt.legend()


mi = find-2
left, bottom, width, height = [0.55, 0.40, 0.3, 0.3]
ax2 = fig.add_axes([left, bottom, width, height])
ax2.plot(V[mi:find+5],murho[mi:find+5],"-o")
ax2.plot([min(V[mi:find+5]),max(V[mi:find+5])],[murhoeff,murhoeff],"--")



plt.show()

print(murhoeff,murho[find],V[find])



hvl = 0.3117 #cm
rho = 2.7 #g/cm^3

mueff = np.log(2)/hvl #1/cm
murhoeff = mueff/rho #cm^2/g

murhoAl = [2.605e+1,3.423e+0,1.131e+0,5.675e-1,3.684e-1,2.778e-1,2.302e-1,2.018e-1,1.832e-1,1.705e-1,1.607e-1,1.533e-1,1.472e-1,1.421e-1,1.378e-1,1.339e-1,1.306e-1,1.275e-1,1.246e-1,1.219e-1,1.196e-1,1.174e-1]

val = 1e10
find = 0
for i in range(len(murho)):
    if(abs(murho[i]-murhoeff) < val):
        val = murho[i]-murhoeff
        find = i
        
fig, ax1 = plt.subplots()


ax1.plot(V,murho,"-",label="Al attenuasjons koef.")
ax1.plot([min(V),max(V)],[murhoeff,murhoeff],"--",label="HVL attenuasjons koef.")
plt.ylabel("$\mu/\\rho$ [cm$^2$/g]",fontsize = 14)
plt.xlabel("Foton energi [keV]",fontsize = 14)
plt.title('Effektiv energi m/Al filter ved HVL attenuasjon koef.', fontsize = 16, fontweight="bold", y=1.08)
plt.legend()

mi = find-2
left, bottom, width, height = [0.55, 0.40, 0.3, 0.3]
ax2 = fig.add_axes([left, bottom, width, height])
ax2.plot(V[mi:find+5],murho[mi:find+5],"-o")
ax2.plot([min(V[mi:find+5]),max(V[mi:find+5])],[murhoeff,murhoeff],"--")


plt.show()
print(murhoeff,murhoAl[find],V[find])



