#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 22 11:34:09 2018

@author: Rafiki
"""

import matplotlib.pyplot as plt
import numpy as np

filt = [0,1,2,3,4,6]
Ir = np.array([0.157, 0.119, 0.096, 0.079, 0.068,	0.052])   

reg = np.polyfit(filt,Ir,2)
msg = ("V(Ir) = %.3f %.3fx + %.3f$x^2$" %(reg[2],reg[1],reg[0]))


plt.plot(filt,Ir,"-o",label=msg)
plt.xlabel("Ekstra Aluminiumsfilter [mm]")
plt.ylabel("Ione rate [nA]")
plt.legend()
plt.title("Ione rate som funksjon ektra aluminiumsfilter")
plt.show()

Irlog = np.log(Ir)
reg = np.polyfit(filt,Irlog,1)
msg = ("V(Ir) = %.3f + %.3fx" %(reg[1],reg[0]))
plt.plot(filt,Irlog,"-o",label=msg)
plt.xlabel("Ekstra Aluminiumsfilter [mm]")
plt.ylabel("log(Ione rate) [nA]")
plt.legend()
plt.title("Ione rate som funksjon ektra aluminiumsfilter")
plt.show()
