#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 23 15:50:34 2018

@author: Rafiki
"""

import matplotlib.pyplot as plt
import numpy as np

I0 = np.linspace(1,10000,10000)
I = I0/2
e = I0*np.exp(np.log(2))

plt.plot(I0,I)
plt.plot(I0,e)
plt.show()